### ISSUE TITLE
After new CSGO update...

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/OneByteLdr#16]
Hi @danielkrupinski 
After new CSGO update (today)... the script show this error

2020-07-17 22:47:36,236 - pymem - DEBUG - Process 3884 is being debugged
Traceback (most recent call last):
  File "OneByteLdr", line 23, in <module>
    address = client.lpBaseOfDll + re.search(rb'.\x55\x6A\x00\x6A\x04',
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by batininhani** [comment]
Change the first byte to 5A. That will work!

**Comment by batininhani** [comment]
Change the first byte to 5A.

**Comment by ghost** [comment]
> Change the first byte to 5A.

Thank you! ♥

**Comment by ghost** [comment]
Hi @batininhani 

**CSGO UPDATE today and new ERROR on LOAD**

2020-08-06 23:00:03,420 - pymem - DEBUG - Process 33988 is being debugged
Traceback (most recent call last):
File "OneByteLdr.py", line 23, in
address = client.lpBaseOfDll + re.search(rb'.\x5A\x6A\x00\x6A\x04',
AttributeError: 'NoneType' object has no attribute 'start'

You can help?

**Comment by batininhani** [comment]
> Change the first byte to 5A.

"69"

**Comment by ghost** [comment]
> > Change the first byte to 5A.
> 
> "69"

thank you
You are always responding
If it's not too much trouble, could you tell me how to find out these things? So I do not bother in the future for the same

**Comment by batininhani** [comment]
@TauCSGO Follow the Daniel's instructions :)

**Comment by TauCSGO** [comment]
> @TauCSGO Follow the Daniel's instructions :)

I need to know how to find the correct answer of the code that I must place, 
re.search(rb'.\x69\x6A\x00\x6A\x04',

is there a program that returns the correct code?
Where should I look for it?

I am new to this and I am trying to learn.
So, in a future update, I won't bother you again

Thank you very much

**Comment by TauCSGO** [comment]
> @TauCSGO Follow the Daniel's instructions :)

New CSGO Update and error :(

2020-09-08 20:21:52,908 - pymem - DEBUG - Process 2028 is being debugged
Traceback (most recent call last):
  File "OneByteLdr.py", line 12, in <module>
AttributeError: 'NoneType' object has no attribute 'start'
[11032] Failed to execute script OneByteLdr

Regards
