### ISSUE TITLE
[QUESTION] Should this fix OBS game capture?

### ISSUE THREAD

**Issue by free0ne87** [danielkrupinski/OneByteLdr#17]
Theoretically this should fix OBS in game capture mode. Can someone confirm?

**Comment by ManISueYou** [comment]
It does not work for me. I can inject with loadlibrary, just OBS does not work.
![image](https://user-images.githubusercontent.com/52098823/88164200-ab88fa00-cbc8-11ea-94a6-0ec600cf08b2.png)
![image](https://user-images.githubusercontent.com/52098823/88164220-b5126200-cbc8-11ea-8dae-4b5ca844c656.png)
![image](https://user-images.githubusercontent.com/52098823/88164247-bcd20680-cbc8-11ea-9395-c9018e046e2e.png)

**Comment by ManISueYou** [comment]
If someone else could get OBS to work please comment back with how. NOT by doing -untrusted.

**Comment by rakion99** [comment]
you need to open csgo first, then patch it with this then you can open obs and will work fine if not move obs folder to c:/windows
i just tested it and works fine the game capture

**Comment by ManISueYou** [comment]
It does work now, thank you.
