### ISSUE TITLE
I don't understand what to do

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/OneByteLdr#2]
I am new to this and I try to learn every day, but I do not understand where to put the code

```
// Restore original NtOpenFile from external process
LPVOID ntOpenFile = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
if (ntOpenFile) {
    char originalBytes[5];
    memcpy(originalBytes, ntOpenFile, 5);
    WriteProcessMemory(csgoProcessHandle, ntOpenFile, originalBytes, 5, NULL);
}
```

I appreciate a little more help, to continue learning and testing

**Comment by SpaceR3** [comment]
are you retarted

thats c++

**Comment by TauCSGO** [comment]
> are you retarted
> 
> thats c++

That your mother is what?
Ah, yes, retarded, that's why you have the round face of down syndrome.
We already know

**Comment by ghost** [comment]
> are you retarted
> 
> thats c++

Reported!

**Comment by LegendaryB** [comment]
Dude you don't need to put the code anywhere. Just execute the python script and you can use LoadLibrary normally again to inject your stuff

**Comment by TauCSGO** [comment]
> Dude you don't need to put the code anywhere. Just execute the python script and you can use LoadLibrary normally again to inject your stuff

Thank you very much, friend for your answer.
I have tested the script and it works perfectly
More than anything my query was referring to what someone who does not have python installed, who does not understand.
Will a phyton script run without having phyton in the system?
Or can create an .exe based on the code that Daniel put?

Sorry for my english

**Comment by ghost** [comment]
> Dude you don't need to put the code anywhere. Just execute the python script and you can use LoadLibrary normally again to inject your stuff

Thank you very much, friend for your answer.
I have tested the script and...

`  File "OneByteLdr.py", line 9
    address = csgo.lpBaseOfDll + re.search(rb'.\x1A\xF6\x45\x0C\x20',
                                                                   ^
SyntaxError: invalid syntax`

**Comment by aftery142** [comment]
> 
> 
> > are you retarted
> > thats c++
> 
> Reported!

-1

**Comment by jxian725** [comment]
> > Dude you don't need to put the code anywhere. Just execute the python script and you can use LoadLibrary normally again to inject your stuff
> 
> Thank you very much, friend for your answer.
> I have tested the script and...
> 
> ` File "OneByteLdr.py", line 9 address = csgo.lpBaseOfDll + re.search(rb'.\x1A\xF6\x45\x0C\x20', ^ SyntaxError: invalid syntax`

Try this: https://github.com/danielkrupinski/OneByteLdr/issues/5
