### ISSUE TITLE
CSGO Update Sep 08 - Bypass Error

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/OneByteLdr#24]
2020-09-08 20:21:52,908 - pymem - DEBUG - Process 2028 is being debugged
Traceback (most recent call last):
  File "OneByteLdr.py", line 12, in <module>
AttributeError: 'NoneType' object has no attribute 'start'
[11032] Failed to execute script OneByteLdr

Regards

**Comment by joshcancode** [comment]
This is happening because of the latest game update. You'll have to wait for Daniel to release updated patterns,

**Comment by rakion99** [comment]
just change the first byte 1A to 1B in line 12

**Comment by ghost** [comment]
> just change the first byte 1A to 1B in line 12

Love you, man!
Thanks!

How can I know what data to change for a future update?
I don't like to bother and I would like to learn

**Comment by danielkrupinski** [comment]
Updated

**Comment by batininhani** [comment]
https://github.com/batininhani/RevokeAlldr/ Have a look! :)
