### ISSUE TITLE
Memject

### ISSUE THREAD

**Issue by AlexanderQueen** [danielkrupinski/OneByteLdr#3]
Can you implent alternative code for Memject?

**Comment by danielkrupinski** [comment]
It doesn't use LoadLibrary.

**Comment by AlexanderQueen** [comment]
loaderParams.loadLibraryA = LoadLibraryA;
loaderParams.rtlZeroMemory = (VOID(NTAPI*)(PVOID, SIZE_T))GetProcAddress(LoadLibraryW(L"ntdll"), "RtlZeroMemory");

**Comment by danielkrupinski** [comment]
This is for resolving imports, it loads only **system dlls** that aren't prohibited.

**Comment by AlexanderQueen** [comment]
Thanks a lot. Congratulation for new release.
