### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by jxian725** [danielkrupinski/OneByteLdr#5]
the script gives me an error when i loaded it with cmd in admin:
[python.exe path] [OneByteLdr.py path]
File "OneByteLdr.py", line 9 address = csgo.lpBaseOfDll + re.search(rb'.\x1A\xF6\x45\x0C\x20', ^ SyntaxError: invalid syntax

And if I directly run the OneByteLdr.py, it pops out a cmd window for a millisecond then nothing happenned, dll is still blocked when injected.

Tried also with VAC Bypass Loader, same problem.

**Comment by danielkrupinski** [comment]
What's your Python version?

**Comment by jxian725** [comment]
> What's your Python version?

The version im using is 2.7 x64

**Comment by jxian725** [comment]
I had triend with version 3.8.3 both 32 and 64 bit and come out with this error.
Traceback (most recent call last):
  File "OneByteLdr.py", line 1, in <module>
    import pymem
ModuleNotFoundError: No module named 'pymem'

**Comment by danielkrupinski** [comment]
Use the latest version of 32-bit Python and install pymem library (preferably version 1.0).

**Comment by jxian725** [comment]
> Use the latest version of 32-bit Python and install pymem library (preferably version 1.0).

Thank you! It works!
