### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xmine7890** [danielkrupinski/OneByteLdr#7]
The token does not have the specified privilege.

Traceback (most recent call last):
  File "OneByteLdr.py", line 4, in <module>
    pm = pymem.Pymem('csgo.exe')
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 45, in __init__
    self.open_process_from_name(process_name)
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 198, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 220, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 2976
@danielkrupinski

**Comment by jxian725** [comment]
> The token does not have the specified privilege.
> 
> Traceback (most recent call last):
> File "OneByteLdr.py", line 4, in
> pm = pymem.Pymem('csgo.exe')
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 45, in **init**
> self.open_process_from_name(process_name)
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 198, in open_process_from_name
> self.open_process_from_id(self.process_id)
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 220, in open_process_from_id
> raise pymem.exception.CouldNotOpenProcess(self.process_id)
> pymem.exception.CouldNotOpenProcess: Could not open process: 2976
> @danielkrupinski

Just run in admin will fix it

**Comment by xmine7890** [comment]
@danielkrupinski sorry i didnot saw the The token does not have the specified privilege.
Thanks now its working.
