### ISSUE TITLE
How does a person without Python?

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/OneByteLdr#9]
Suppose someone doesn't have visual studio or python
Maybe the PC belongs to a family member and he cannot install phyton
What does that person do?
it is possible to create an .exe similar to the Vac Bypass?

**Comment by danielkrupinski** [comment]
Then you can use code from https://github.com/danielkrupinski/OneByteLdr/blob/master/README.md#alternative-approach

**Comment by Nesc4uu** [comment]
And i put it in my injector ?

**Comment by ghost** [comment]
> And i put it in my injector ?

I try to put this code in the inyector

> // Restore original NtOpenFile from external process
> LPVOID ntOpenFile = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
> if (ntOpenFile) {
>     char originalBytes[5];
>     memcpy(originalBytes, ntOpenFile, 5);
>     WriteProcessMemory(csgoProcessHandle, ntOpenFile, originalBytes, 5, NULL);
> }

but i have this erros
I am very new on this thinks

`expected a declaration`
`syntax error "if"`
`syntax error: missing ';' before '{'	`

**Comment by ghost** [comment]
I have tried the python version and it works OK
I even did a .bat to avoid writing

Now I only hope to solve the part in C ++ to be able to put the code inside the injector

Thanks for your work @danielkrupinski 
Next week I will have some balance in paypal and I will make a donation ♥

**Comment by Nesc4uu** [comment]
Pls teach me how i can use it? i'm taking the  "no module named pymem" error

**Comment by ghost** [comment]
> Pls teach me how i can use it? i'm taking the "no module named pymem" error

- Download the latest version of Python 3 (https://www.python.org/downloads/)
- In your Phyton installed directory: (example: C:\Users\YOUR_USERNAME\AppData\Local\Programs\Python\Python38-32
-- Open CMD and do pip install pymem
-- Open CMD and do pip install win32api
- Copy OneByteLdr.py in Phyton installed directory
- Open CSGO
- Type: python OneByteLdr.py
- Inject the cheat

**Comment by Nesc4uu** [comment]
![15933907430935779138994517437683](https://user-images.githubusercontent.com/48437066/85962398-e790bc80-b986-11ea-83af-563a608e53b0.jpg)
btw it is portuguese

**Comment by ghost** [comment]
Go to script folder an copy pip, pip3.8 and pip3 in the phyton38-38 folder

**Comment by Nesc4uu** [comment]
oh ok its working, wait

**Comment by Nesc4uu** [comment]
where i can found win32api?

**Comment by ghost** [comment]
> win32api

Try winout win32api
Works fine

**Comment by Nesc4uu** [comment]
i'll try, thanks for now :)

**Comment by Nesc4uu** [comment]
i think osiris is crashing my game '-'

**Comment by ghost** [comment]
> i think osiris is crashing my game '-'

re-download Osiris and compile new dll
